[math] Use Math Transformation Services as Profiles
smarthomej/addons pull request #231
Opened 2021-11-27 17:41 UTC by cweitkamp

- Use Math Transformation Services as Profiles

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

2021-11-27 18:22 UTC, J-N-K requested changes
Nice, I have left some comments.

2021-11-27 18:22 UTC, J-N-K commented on bundles/org.smarthomej.transform.math/README.md
> +Number secondsToMinutes "Time [%d]" { channel="<channelUID>" [profile="transform:DIVIDE, dvisor=60] }
```suggestion
Number secondsToMinutes "Time [%d]" { channel="<channelUID>" [profile="transform:DIVIDE, divisor=60] }
```

2021-11-27 18:22 UTC, J-N-K commented on bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/binding/math/internal/AbstractMathTransformationService.java
> +    private final Logger logger = LoggerFactory.getLogger(getClass());
nice

2021-11-27 18:22 UTC, J-N-K commented on bundles/org.smarthomej.transform.math/src/main/java/org/smarthomej/binding/math/internal/profiles/MathTransformationProfileFactory.java
> +    private TransformationService addTransformationService;
```suggestion
    private @NonNullByDefault({}) TransformationService addTransformationService;
```

seems more consistent with the other null-annotations code style

2021-11-27 18:22 UTC, J-N-K commented on bundles/org.smarthomej.transform.math/src/main/resources/OH-INF/i18n/transform_de.properties
> +profile.config.transform.ADD.addend.description = Wert, der zu dem item state addiert wird.
```suggestion
profile.config.transform.ADD.addend.description = Wert, der zu dem Item State addiert wird.
```

2021-11-28 11:48 UTC, cweitkamp commented
Thanks for your quick review. I added unit tests, renamed packages and incorporated your comments from review .

2021-11-28 13:04 UTC, J-N-K approved these changes

2021-11-28 13:04 UTC, merged