[viessmann] add status channel for OneTimeCharge
smarthomej/addons pull request #415
Opened 2022-11-12 17:08 UTC by rogrun

This PR: 
Adds a channel which provides the state of OneTimeCharge. (Device Thing)
Adds the ability to disable polling. (Bridge Thing)
Adds channels for manual polling. (Bridge Thing)

Improves the channel type for channels w/o commands to read-only.

Also fixes some typo.

Signed-off-by: Ronny Grun <ronny.grun@t-online.de>

2022-11-12 17:08 UTC, rogrun commented
Ready for Review.

2022-11-12 19:03 UTC, J-N-K requested changes
Thanks for all the clean-up. I only left some minor comments.

2022-11-12 19:03 UTC, J-N-K commented on bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/config/BridgeConfiguration.java
> +    public Boolean disablePolling = false;
```suggestion
    public boolean disablePolling = false;
```

Use primitives where possible.

2022-11-12 19:03 UTC, J-N-K commented on bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/DeviceHandler.java
> +                                executorService.schedule(this::initChannelState, initStateDelay, TimeUnit.SECONDS);
Is there a reason why you don't use the integrated `scheduler`?

2022-11-12 19:03 UTC, J-N-K commented on bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/ViessmannBridgeHandler.java
> +        }
```suggestion
        if (channelUID.getId().equals(CHANNEL_RUN_QUERY_ONCE) && OnOffType.ON.equals(command)) {
            logger.debug("Received command: CHANNEL_RUN_QUERY_ONCE");
            pollingFeatures();
            updateState(CHANNEL_RUN_QUERY_ONCE, OnOffType.OFF);
        }
```

also below

2022-11-12 19:03 UTC, J-N-K commented on bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/ViessmannBridgeHandler.java
> +        if (errorChannelsLinked() && !config.disablePolling) {
```suggestion
        if (!config.disablePolling && errorChannelsLinked()) {
```

Might not be the biggest improvement, but the `!config.disablePolling` check is cheap compared to the `isLinked` check, so it's better to do it first.

2022-11-13 07:22 UTC, J-N-K submitted a review, later dismissed

2022-11-13 07:42 UTC, rogrun commented on bundles/org.smarthomej.binding.viessmann/src/main/java/org/smarthomej/binding/viessmann/internal/handler/DeviceHandler.java
> +                                executorService.schedule(this::initChannelState, initStateDelay, TimeUnit.SECONDS);
I don't know the integrated scheduler. I changed it. Thanks!

2022-11-13 07:54 UTC, J-N-K approved these changes

2022-11-13 07:54 UTC, merged