[androiddebugbridge] add fallback to start package channel
smarthomej/addons pull request #49
Opened 2021-03-26 00:18 UTC by GiviMAD

Add fallback to the start package channel, using monkey command to open applications instead of am on devices which doesn't support the -n parameter (devices under android 8).

2021-03-27 10:32 UTC, Trinitus01 commented
Does the openURL work on your device? (Because of the -a and -d parameters? Or does it also need a fallback?

2021-03-27 10:34 UTC, Trinitus01 commented
Should i remove all the result empty checks (except the one for the logcat result) in a new pr or will you change it?

2021-03-28 11:20 UTC, GiviMAD commented
Hi,
The openURL channel is working correctly on my device (android 7.1.2) so no need for a fallback on my side.
And yes I think that we can remove those empty results and raised exception exceeding the ones that depends on a log rotation as you explained to me earlier on a separate pr.

2021-03-30 06:37 UTC, Trinitus01 requested changes

2021-03-30 11:27 UTC, J-N-K commented on bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
> +    private boolean fallbackStartPackage = false;
If you do that, please name it "allowlist/denylist" or "accesslist/blocklist" instead of "whitelist/blacklist". Thanks.

2021-03-31 18:08 UTC, Trinitus01 submitted a review, later dismissed

2021-03-31 19:43 UTC, J-N-K commented
I‘m not sure why this happened, but can you please rebase on main? There are some changes which do not belong here.

2021-03-31 20:01 UTC, Trinitus01 commented
There is some robot binding stuff?!?

2021-03-31 20:33 UTC, GiviMAD commented
My fault, it's fixed now.

2021-03-31 20:37 UTC, Trinitus01 commented on bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
> +        if (channelFallbackMap.get(HDMI_STATE_CHANNEL) == FallbackModes.LOGCAT) {
I prefer equals instead of '=='.
But as i read it seems to be fine to use '==' for enum.

2021-03-31 20:38 UTC, Trinitus01 approved these changes

2021-04-01 09:18 UTC, J-N-K requested changes

2021-04-01 09:18 UTC, J-N-K commented on bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
> +    private HashMap<String, FallbackModes> channelFallbackMap = new HashMap<>();
```suggestion
    private Map<String, FallbackModes> channelFallbackMap = new HashMap<>();
```

2021-04-01 09:18 UTC, Trinitus01 commented
For isHDMIOn() it seems the first command can fail sometimes but the fallback command is not supported by the device. If this happens it never goes back to the first command. I don't know why it can fail, maybe the result is empty between it switches from 0 to 1 and the cat fetches the result between the two states?!? To get out of the fallback we could remove the fallback from the map if the fallback method runs into an exception. So it will try both (or more fallbacks in the future) again. What do you think about that? How to ensure it tries the first command again if both method fail?

2021-04-01 09:37 UTC, Trinitus01 requested changes

2021-04-01 09:37 UTC, Trinitus01 commented on bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
> +        throw new AndroidDebugBridgeDeviceReadException(HDMI_STATE_CHANNEL, result);
```suggestion
        channelFallbackMap.remove(HDMI_STATE_CHANNEL);
        throw new AndroidDebugBridgeDeviceReadException(HDMI_STATE_CHANNEL, result);
```

2021-04-01 09:37 UTC, Trinitus01 commented on bundles/org.smarthomej.binding.androiddebugbridge/src/main/java/org/smarthomej/binding/androiddebugbridge/internal/AndroidDebugBridgeDevice.java
> +        throw new AndroidDebugBridgeDeviceReadException(HDMI_STATE_CHANNEL, result);
To the case it never tries the first method again and the fallback is not supported by the device.

2021-04-01 17:20 UTC, Trinitus01 approved these changes

2021-04-02 06:51 UTC, J-N-K approved these changes

2021-04-02 06:51 UTC, merged